services:
  test-api:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    container_name: test-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgresql://user:pass@host/name
      - TOKEN_KEY=secret
      - REFRESH_TOKEN_KEY=secret1